# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Leoui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Leoui(object):
    def setupUi(self, Leoui):
        Leoui.setObjectName("Leoui")
        Leoui.resize(1160, 832)
        self.centralwidget = QtWidgets.QWidget(Leoui)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-30, -20, 1261, 871))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("G.U.I Material/B.G/Black_Template.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(410, 180, 55, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(770, 10, 441, 471))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("G.U.I Material/B.G/Iron_Template_1.gif"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(0, 10, 871, 141))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("G.U.I Material/B.G/original-10771-1637089187-9.png"))
        self.label_4.setScaledContents(False)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(670, 20, 261, 141))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("G.U.I Material/B.G/images.jpeg"))
        self.label_5.setScaledContents(False)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(0, -20, 321, 231))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("G.U.I Material/ExtraGui/initial.gif"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(700, 500, 451, 221))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("G.U.I Material/ExtraGui/B.G_Template_1.gif"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(700, 730, 221, 51))
        self.pushButton.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";\n"
"font: 12pt \"Segoe MDL2 Assets\";")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(930, 730, 221, 51))
        self.pushButton_2.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 500, 701, 351))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(0, 250, 681, 31))
        self.lineEdit.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.terminalOutputBox = QtWidgets.QPlainTextEdit(self.frame)
        self.terminalOutputBox.setGeometry(QtCore.QRect(0, 0, 681, 241))
        self.terminalOutputBox.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.terminalOutputBox.setObjectName("terminalOutputBox")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setGeometry(QtCore.QRect(570, 250, 111, 31))
        self.pushButton_3.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";\n"
"font: 12pt \"Segoe MDL2 Assets\";")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(330, 160, 481, 321))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("G.U.I Material/B.G/techcircle.gif"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(70, 190, 201, 181))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("G.U.I Material/B.G/tech loading-cropped.gif"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(70, 170, 201, 181))
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("G.U.I Material/B.G/listening.gif"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(70, 190, 201, 181))
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("G.U.I Material/B.G/speaking.gif"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(60, 180, 211, 181))
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("G.U.I Material/VoiceReg/sleepmode.gif"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        Leoui.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Leoui)
        self.statusbar.setObjectName("statusbar")
        Leoui.setStatusBar(self.statusbar)

        self.retranslateUi(Leoui)
        QtCore.QMetaObject.connectSlotsByName(Leoui)

    def retranslateUi(self, Leoui):
        _translate = QtCore.QCoreApplication.translate
        Leoui.setWindowTitle(_translate("Leoui", "MainWindow"))
        self.label_2.setText(_translate("Leoui", "TextLabel"))
        self.pushButton.setText(_translate("Leoui", "START"))
        self.pushButton_2.setText(_translate("Leoui", "EXIT"))
        self.terminalOutputBox.setPlainText(_translate("Leoui", "------------------------------------- Terminal Output Goes Here -------------------------------------"))
        self.pushButton_3.setText(_translate("Leoui", "ENTER"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Leoui = QtWidgets.QMainWindow()
    ui = Ui_Leoui()
    ui.setupUi(Leoui)
    Leoui.show()
    sys.exit(app.exec_())
